servers:
- name: Django + Graphene v3
  path: servers/django-graphene/

- name: Django + Strawberry
  path: servers/django-strawberry/

- name: Django + Strawberry Async
  path: servers/django-strawberry-async/

# - name: Django + Graphql Core v3
#   path: servers/django-graphql-core/

- name: Django Rest Framework
  path: servers/django-rest-framework/

# - name: Django Plain JSON
#   path: servers/django-plain-json/

# - name: Starlette + Graphene v3
#   path: servers/starlette-graphene/

# - name: Starlette + Strawberry
#   path: servers/starlette-strawberry/

# - name: Starlette + Graphql Core v3
#   path: servers/starlette-graphql-core/

# - name: Starlette Plain JSON
#   path: servers/starlette-plain-json/

- name: SQLAlchemy + Strawberry
  path: servers/fastapi-sqlalchemy/

- name: SQLAlchemy + FastAPI REST
  path: servers/fastapi-sqlalchemy/

queries:
- name: Top 250 rated movies
  runner: queries/top-movies.js
  server_overrides:
    - name: Django Rest Framework
      runner: queries/top-movies-rest.js
    - name: Django Plain JSON
      runner: queries/top-movies-rest.js
    - name: SQLAlchemy + FastAPI REST
      runner: queries/top-movies-rest.js
